# Root for default board (platform-specific stuff)
board-dir : '../boards/firechip'

# Stores all outputs (binaries and images)
image-dir : '../images'

# Default linux source
linux-dir : '../riscv-linux'

# Default pk source
pk-dir : '../riscv-pk'

# Runtime Logs
log-dir : '../logs' 

# SW-simulation outputs
res-dir : '../runOutput'

# Default parallelism level to use in subcommands (mostly when calling 'make')
# '' means unbounded
jlevel : ''

# Number of extra bytes to leave free by default in filesystem images
rootfs-margin : '256MiB'
